package pe.tata.bfp.ibs.tarjeta.modelo;

public class CDQueryTarjetaCredito {
	
	public String CNS_SALDO_TARJETA_CREDITO = "";
	
	/**
	 *	Descripción		:	Query embebido IBS de tarjetas de crédito empresarial, evaluado por su código único de cliente
	 *						empresarial asociado con sus vinculados 
	 */
	public String querySaldoTarjetaCredito(long piCodigoEmpresa){
		
		CNS_SALDO_TARJETA_CREDITO = "SELECT 			TJ.CUSEMP AS CodigoEmpresa, TC.CUSNA1 AS NombreEmpresa, TJ.NROPAN, "
				+ "				TJ.NROTIT, TJ.NOMB30 AS NombreTarjeta, TJ.ESTBCO AS EstadoTarjetaBanco, "
				+ "				(SELECT 	TBL.DESCOR "
				+ "				   FROM   	BFPCYFILES.VPLUT04	TBL "
				+ "				   WHERE	TBL.DIGIDE = 801 AND "
				+ "				   			TBL.CODTAB = TJ.ESTBCO "
				+ "				) AS EstadoTarjetaBanco, "
				+ "				TJ.CUSCUN AS CodigoVinculado, TV.CUSNA1, TJ.CICFAC AS CicloFacturacion,  "
				+ "				TJ.LINCRE AS LineaCredito, TS.DISCON AS SaldoDisponibleConsumo,  "
				+ "				TS.LINDIS AS LineaCreditoDisposicion, TS.DISDIS AS SaldoDisposicionEfectivo, "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.DIAEST) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)),2) || "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.MESEST) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)), 2) || "
				+ "				CAST((SELECT		MAX(TP.AÑOEST) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(04)) AS DDMMAAAAFacturacion, "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.DIAULP) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)), 2) || "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.MESULP) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)), 2) || "
				+ "				CAST((SELECT		MAX(TP.AÑOULP) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(04)) AS DDMMAAAAPago, "
				+ "				COALESCE((SELECT			TP.IMPCAR "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	604) "
				+ "				), 0) AS PagoMinimoMN, "
				+ "				COALESCE((SELECT			TP.SALACT "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	604) "
				+ "				), 0) AS PagoTotalMN, "
				+ "				COALESCE((SELECT			TP.IMPCAR "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	840) "
				+ "				), 0) AS PagoMinimoME, "
				+ "				COALESCE((SELECT			TP.SALACT "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	840) "
				+ "				),0) AS PagoTotalME "
				+ "   FROM   		BFPCYFILES.VPLUS01  	TJ "
				+ "   INNER JOIN	BFPCYFILES.CUMST		TC "
				+ "   			ON	(TC.CUSCUN	= TJ.CUSEMP) "
				+ "   INNER JOIN	BFPCYFILES.CUMST		TV "
				+ "   			ON	(TV.CUSCUN	= TJ.CUSCUN) "
				+ "   INNER JOIN	BFPCYFILES.VPLU81PM		TS "
				+ "   			ON	(TS.PANBAN		=	TJ.NROPAN AND "
				+ "   			     TS.NROTAR		=	TJ.NROTIT) "
				+ "   WHERE		(TJ.CUSEMP 	!= 0 AND TS.MONSAL	=	840) AND "
				+ "         TJ.CUSEMP = " + piCodigoEmpresa; 
		
		return CNS_SALDO_TARJETA_CREDITO;
	}

	/**
	 *	Descripción		:	Query embebido IBS de tarjetas de crédito empresarial, todos las tarjetas vinculadas 
	 */
	
	public String queryTotalSaldoTarjetaCredito(){
		
		CNS_SALDO_TARJETA_CREDITO = "SELECT 			TJ.CUSEMP AS CodigoEmpresa, TC.CUSNA1 AS NombreEmpresa, TJ.NROPAN, "
				+ "				TJ.NROTIT, TJ.NOMB30 AS NombreTarjeta, TJ.ESTBCO AS EstadoTarjetaBanco, "
				+ "				(SELECT 	TBL.DESCOR "
				+ "				   FROM   	BFPCYFILES.VPLUT04	TBL "
				+ "				   WHERE	TBL.DIGIDE = 801 AND "
				+ "				   			TBL.CODTAB = TJ.ESTBCO "
				+ "				) AS EstadoTarjetaBanco, "
				+ "				TJ.CUSCUN AS CodigoVinculado, TV.CUSNA1, TJ.CICFAC AS CicloFacturacion,  "
				+ "				TJ.LINCRE AS LineaCredito, TS.DISCON AS SaldoDisponibleConsumo,  "
				+ "				TS.LINDIS AS LineaCreditoDisposicion, TS.DISDIS AS SaldoDisposicionEfectivo, "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.DIAEST) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)),2) || "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.MESEST) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)), 2) || "
				+ "				CAST((SELECT		MAX(TP.AÑOEST) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(04)) AS DDMMAAAAFacturacion, "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.DIAULP) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)), 2) || "
				+ "				RIGHT(REPEAT('0', 2) || CAST((SELECT		MAX(TP.MESULP) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(02)), 2) || "
				+ "				CAST((SELECT		MAX(TP.AÑOULP) "
				+ "					FROM	BFPCYFILES.VPLUS69	TP "
				+ "   					WHERE	(TP.NROP16	=	TJ.NROPAN AND "
				+ "			   				 TP.NROT16  =	TJ.NROTIT) "
				+ "				) AS VARCHAR(04)) AS DDMMAAAAPago, "
				+ "				COALESCE((SELECT			TP.IMPCAR "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	604) "
				+ "				), 0) AS PagoMinimoMN, "
				+ "				COALESCE((SELECT			TP.SALACT "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	604) "
				+ "				), 0) AS PagoTotalMN, "
				+ "				COALESCE((SELECT			TP.IMPCAR "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	840) "
				+ "				), 0) AS PagoMinimoME, "
				+ "				COALESCE((SELECT			TP.SALACT "
				+ "					FROM		BFPCYFILES.VPLUS85	TP "
				+ "					WHERE		(TP.NROP16	=	TJ.NROPAN AND "
				+ "								 TP.MONSAL	=	840) "
				+ "				),0) AS PagoTotalME "
				+ "   FROM   		BFPCYFILES.VPLUS01  	TJ "
				+ "   INNER JOIN	BFPCYFILES.CUMST		TC "
				+ "   			ON	(TC.CUSCUN	= TJ.CUSEMP) "
				+ "   INNER JOIN	BFPCYFILES.CUMST		TV "
				+ "   			ON	(TV.CUSCUN	= TJ.CUSCUN) "
				+ "   INNER JOIN	BFPCYFILES.VPLU81PM		TS "
				+ "   			ON	(TS.PANBAN		=	TJ.NROPAN AND "
				+ "   			     TS.NROTAR		=	TJ.NROTIT) "
				+ "   WHERE		(TJ.CUSEMP 	!= 0 AND TS.MONSAL	=	840) ";
		
		return CNS_SALDO_TARJETA_CREDITO;
	}	
}
